### DISCUSSION TITLE
Building for target x86_64-pc-windows-gnu (on GHA)

### DISCUSSION THREAD

**Discussion by KillTheMule** [fltk-rs/fltk-rs#1219] [Q&A] [answered]
Hey, I'm trying to switch to the `x86_64-pc-windows-gnu` toolchain, but fltk-rs seems to be givin me trouble. I've disabled caching and I'm using the `fltk-bundled` flag. I'm getting this error:

> error: could not find native static library `cfltk`, perhaps an -L flag is missing?
> error: could not compile `fltk-sys` due to previous error
> warning: build failed, waiting for other jobs to finish...

Everything I've read on the gh page and the FAQ makes me believe this should simply work with the new target (I've used the msvc target before), so I'm a bit stumped on what I'd need to do.

I'd be grateful for any pointers!

**Comment by MoAlyousef** [comment, marked as answer]
Hi
It might be that the gh action doesn't have the windows-gnu target installed.
You can try using actions-rs:
https://github.com/MoAlyousef/fltk-gha
The repo builds correctly with `fltk-bundled` for windows-gnu target with the following yaml:
```yaml
name: Build
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions-rs/toolchain@v1.0.6
        with: 
          toolchain: stable-gnu
          profile: minimal
          default: true
      - uses: actions/checkout@v2
      - name: Build binary
        run: |
          cargo build --verbose --release
```
