### DISCUSSION TITLE
I'm new to this Do i need to install the FLTK library

### DISCUSSION THREAD

**Discussion by goodylili** [fltk-rs/fltk-rs#1249] [Q&A]
Do I need to install any libraries to use this package like how I have to install GTK to use GTK-rs 

Or just add to my dependencies and import

Please help

**Comment by MoAlyousef** [comment]
You can check the dependencies here:
https://github.com/fltk-rs/fltk-rs#dependencies

You can also use a bundled form of fltk, which wouldn't require dependencies apart from a Rust compiler.
```toml
[dependencies]
fltk = { version = "1.3", features = ["fltk-bundled"] }
```
