### DISCUSSION TITLE
Changing dock icon on macOS

### DISCUSSION THREAD

**Discussion by woj-tek** [fltk-rs/fltk-rs#1367] [General]
Hi,
I found I can change window icon with `window.set_icon(Some(image));` (vide https://github.com/fltk-rs/fltk-rs/discussions/506). Is there a possibility to change icon displayed in macOS's dock?

**Comment by MoAlyousef** [comment]
Hi
You would have to use [cargo-bundle](https://github.com/burtonageo/cargo-bundle) and modify your Cargo.toml:
```toml
[package.metadata.bundle]
identifier = "io.github.woj-tek" # required for macos
icon = ["assets/icon.png"] # points to your icon
```

Then run cargo bundle --release. This will create a .app file (really a special folder on macos which can be double clicked to launch an app), which is what distinguishes app bundles from ordinary command line executables.
