### DISCUSSION TITLE
cross building is not working with latest release

### DISCUSSION THREAD

**Discussion by cstkingkey** [fltk-rs/fltk-rs#1659] [General]
osxcross: warning: '-mmacosx-version-min=' (10.0.0 != 10)
  osxcross: error: libc++ requires '-mmacosx-version-min=10.7' (or later)
  osxcross: error: while detecting target

I'm setting MACOSX_DEPLOYMENT_TARGET=10.13

**Comment by MoAlyousef** [comment]
Can you check with the current master branch?
```toml
[dependencies]
fltk = "^1.5"

[patch.crates-io]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
```
