### DISCUSSION TITLE
Windows build problem

### DISCUSSION THREAD

**Discussion by jhill1440** [fltk-rs/fltk-rs#940] [Q&A]
I have installed rust on linux and MacOS and got my project to build.  I installed rust on a fresh Windows 10 machine and cannot get my fltk project to build.  I have installed the VC buildtools C++ module. I can build the hello world program and that works fine.  I get getting errors about linking with link.exe failing code 1120.  Any idea as to what could be the problem.

**Comment by MoAlyousef** [comment]
What’s the output of cargo build -vv?

There are instructions for windows here:
https://github.com/fltk-rs/fltk-rs/wiki/Setup#windows-msvc-toolchain

you can also try the bundled version:

```toml
[dependencies]
fltk = { version = "^1.2", features = ["fltk-bundled"] }
```
