### ISSUE TITLE
[BUG] Loading BMP image from bytes

### ISSUE THREAD

**Issue by DBLouis** [fltk-rs/fltk-rs#1038]
Loading a BMP image from bytes with `include_bytes!` and `BmpImage::from_data` fails with `ImageFormatError`.

Please try the example in this commit: DBLouis/fltk-rs@3c7cc90.

**Comment by MoAlyousef** [comment]
I've pushed a fix in master. Can you try again using:
```toml
[dependencies]
fltk = { version = "^1.2", git = "https://github.com/fltk-rs/fltk-rs" }
```
