### ISSUE TITLE
[BUG]v1.2.22 broken vs2022 building

### ISSUE THREAD

**Issue by cstkingkey** [fltk-rs/fltk-rs#1058]
with v1.2.22, building using vs2022 fails with error: failed to run custom build command for `fltk-sys v1.2.22`
thread 'main' panicked at 'Visual studio version detected but this crate doesn't know how to generate cmake files for it, can the `cmake` crate be updated?'

works with v1.2.21.

**Comment by MoAlyousef** [comment]
The build will use the latest version of cmake-rs, unfortunately VS2022 support wasn’t released yet:
https://github.com/alexcrichton/cmake-rs/issues/135

You’ll have to use either the use-ninja feature or use an older version of VS.

**Comment by cstkingkey** [comment]
works with use-ninja. Thanks for your work.
by the way, is there any way to set features based on target?

**Comment by MoAlyousef** [comment]
Not directly for features, however you can specify target specific deps along with their features:
```toml
[target.'cfg(target_os = "windows").dependencies] # or [target.x86_64-pc-windows-msvc.dependencies]
fltk = { version = "1.2", features = ["use-ninja"] }



[target.'cfg(not(target_os = "windows")).dependencies]
fltk = "1.2"
```
