### ISSUE TITLE
FileChooser::set_ok_label does not work

### ISSUE THREAD

**Issue by abau** [fltk-rs/fltk-rs#1137]
Calling `dialog.set_ok_label("foo")` results gives

![Screenshot_20220214_162702](https://user-images.githubusercontent.com/4090497/153893721-d445ff98-1346-4a7e-80ab-f8fd5726c4af.png)

on my machine instead of "foo" as label.

```
$ uname -srv
Linux 5.16.5-arch1-1 #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000
```

**Comment by MoAlyousef** [comment]
Thanks for the report. I've pushed a fix to the master branch.
You can try it using:
```toml
[dependencies]
fltk = { version = "1.2.31", git = "https://github.com/fltk-rs/fltk-rs" }
```
