### ISSUE TITLE
[BUG] BrowserExt::set_icon() leak caused by BrowserExt::clear()

### ISSUE THREAD

**Issue by captchaKing** [fltk-rs/fltk-rs#1158]
## Describe the bug
Sequence of function calls to MultiBrowser in an infinite loop causes memory leak (1GB per second for my image):
clear(), add() and set_icon()

## Desktop info
 - OS: Pop!_OS 21.10
 - Version 1.2

## Additional info
Just repeated calls to set_icon() are fine, but it starts to leak with clear()

**Comment by captchaKing** [comment]
Sorry i screwed title

**Comment by MoAlyousef** [comment]
Hi
Thanks for the report. Can you try building against the latest master:
```toml
[dependencies]
fltk = { version = "1.3.1", git = "https://github.com/fltk-rs/fltk-rs" }
```
