### ISSUE TITLE
[BUG] method `fltk::frame::Frame::set_label ` inappropriately automatically redraw

### ISSUE THREAD

**Issue by Jaffe2718** [fltk-rs/fltk-rs#1409]
# Is this a bug?
From the [official documentation](https://docs.rs/fltk/latest/fltk/), it seem that
invoke the method `fltk::frame::Frame::set_label` will not automatically redraw the
widget. However, in the example code, it seems that the widget is redrawn in `src/main.rs`:
    
```rust
// src/main.rs
use fltk::{app, frame::Frame, prelude::*, window::Window};

fn main() {
    let _app = app::App::default();
    let mut win = Window::default().with_size(400, 300);
    let mut _frame = Frame::default().with_size(200, 100).center_of(&win);
    let tags = ["Hello Word", "fltk-rs 1.4.4"];
    let mut flag = false;
    win.add(&_frame);
    win.show();
    while _app.wait() {
        if flag {
            _frame.set_label(tags[0]);
        } else {
            _frame.set_label(tags[1]);
        }
        flag = !flag;
    }

}
```

This is the `Cargo.toml` file:
```toml
[package]
name = "bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version="1.4.4", features = ["fltk-bundled"]}
```

I am using `fltk-rs 1.4.4` on `Windows 11` with `rustc 1.69.0 (84c898d65 2023-04-16)`.
When I compile and run the code, the label of the frame will automatically redrawn. Is this a bug?
