### ISSUE TITLE
How to run fltk-rs in win 7

### ISSUE THREAD

**Issue by xiandaoyan** [fltk-rs/fltk-rs#1421]
How to resolve the two questions in win 7?

  = note: ld: cannot find **-lgdiplus**: No such file or directory
          ld: cannot find **-lsupc++**: No such file or directory

**Comment by MoAlyousef** [comment]
Hi

Please don’t ignore issue templates!

What’s in your Cargo.toml?
What’s the output of `cargo clean && cargo build -vv`?

For the first question, you can use:
```toml
[dependencies]
fltk = { version = "1.4", features = ["no-gdiplus"] }
```
in your Cargo.toml. 

For the second question, this is the C++ support library, it usually comes with g++ (the gnu C++ compiler), which you appear to be using.
