### ISSUE TITLE
[BUG]最新版本无法通过编译 The latest version cannot be compiled.

### ISSUE THREAD

**Issue by loyoi** [fltk-rs/fltk-rs#1661]
## Describe the bug
使用最新版本 `fltk = "1.5"` 默认编译会是下面这个错误
```
  --- stderr
  error: patch failed: src/Fl_win32.cxx:1351
  error: src/Fl_win32.cxx: patch does not apply
```

## To Reproduce
// Cargo.toml
```toml
[dependencies]
fltk = "~1.4" # 使用1.4版本就可以直接编译通过，使用1.5 会报这个错误 You can compile it directly with version 1.4, but you'll get this error with version 1.5.
```

// src/main.rs
```rust
use fltk::{app, prelude::*, window::Window};
fn main() {
    let app = app::App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    wind.end();
    wind.show();
    app.run().unwrap();
}
```

## Desktop info
 - OS: Windows 10 x64
 - Version [e.g. 1.4.2]
 - Display server on linux (wayland or x11)
