### ISSUE TITLE
center_screen breaks when updating from 1.0.18 to 1.0.19

### ISSUE THREAD

**Issue by abau** [fltk-rs/fltk-rs#742]
```
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dependencies]
fltk = "=1.0.19"
```
and
```
use fltk::app::App;
use fltk::prelude::{GroupExt, WidgetExt, WindowExt};
use fltk::window::Window;

fn main() {
    let app = App::default();
    let mut w = Window::default().with_size(100, 100).center_screen();

    w.end();
    w.show();

    app.run().unwrap();
}
```
gives me an off-center window. Fixing fltk's version to `"=1.0.18"` in the Cargo file gives me a perfectly centered window.

PS Thanks for your work on fltk-rs!

**Comment by MoAlyousef** [comment]
Hi
There was a regression in FLTK screen driver code which was reverted recently. Can you try building against the master branch:
```toml
[dependencies]
fltk = { version = "=1.0.20", git = "https://github.com/fltk-rs/fltk-rs" }
```
This version should be published soon. Just have some more checks to do
